name = "makemock"
compatibility_date = "2024-04-03"

main = "src/worker.js"
assets = { directory = "./dist", binding = "ASSETS" }

[[routes]]
pattern = "makemock.williamfinken.com"
custom_domain = true
